# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - main
      - '**'  # Matches any branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages (main)
        if: github.ref == 'refs/heads/main'
        id: deployment-main
        uses: actions/deploy-pages@v4
        with:
          path: '.'

      - name: Deploy to GitHub Pages (other branches)
        if: github.ref != 'refs/heads/main'
        id: deployment-other
        uses: actions/deploy-pages@v4
        with:
          path: ${{ github.ref_name }}

